server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/office/workspaces/poc/spring-config/config-server/config-repo
          clone-on-start: true
